In [1]:
%%capture
!pip install hierarchicalforecast statsforecast

In [2]:
import numpy as np
import pandas as pd

In [3]:
Y_df = pd.read_csv('https://raw.githubusercontent.com/Nixtla/transfer-learning-time-series/main/datasets/tourism.csv')

In [4]:
Y_df

       Quarter           Region            State   Purpose       Trips
0      1998 Q1         Adelaide  South Australia  Business  135.077690
1      1998 Q2         Adelaide  South Australia  Business  109.987316
2      1998 Q3         Adelaide  South Australia  Business  166.034687
3      1998 Q4         Adelaide  South Australia  Business  127.160464
4      1999 Q1         Adelaide  South Australia  Business  137.448533
...        ...              ...              ...       ...         ...
24315  2016 Q4  Yorke Peninsula  South Australia  Visiting   33.672151
24316  2017 Q1  Yorke Peninsula  South Australia  Visiting   46.223014
24317  2017 Q2  Yorke Peninsula  South Australia  Visiting   50.582837
24318  2017 Q3  Yorke Peninsula  South Australia  Visiting   27.766728
24319  2017 Q4  Yorke Peninsula  South Australia  Visiting   46.281578

[24320 rows x 5 columns]

In [5]:
Y_df = Y_df.rename({'Trips': 'y', 'Quarter': 'ds'}, axis=1)
Y_df

            ds           Region            State   Purpose           y
0      1998 Q1         Adelaide  South Australia  Business  135.077690
1      1998 Q2         Adelaide  South Australia  Business  109.987316
2      1998 Q3         Adelaide  South Australia  Business  166.034687
3      1998 Q4         Adelaide  South Australia  Business  127.160464
4      1999 Q1         Adelaide  South Australia  Business  137.448533
...        ...              ...              ...       ...         ...
24315  2016 Q4  Yorke Peninsula  South Australia  Visiting   33.672151
24316  2017 Q1  Yorke Peninsula  South Australia  Visiting   46.223014
24317  2017 Q2  Yorke Peninsula  South Australia  Visiting   50.582837
24318  2017 Q3  Yorke Peninsula  South Australia  Visiting   27.766728
24319  2017 Q4  Yorke Peninsula  South Australia  Visiting   46.281578

[24320 rows x 5 columns]

In [6]:
Y_df.insert(0, 'Country', 'Australia')
Y_df

,Country,ds,Region,State,Purpose,y
0,Australia,1998 Q1,Adelaide,South Australia,Business,135.077690
1,Australia,1998 Q2,Adelaide,South Australia,Business,109.987316
2,Australia,1998 Q3,Adelaide,South Australia,Business,166.034687
3,Australia,1998 Q4,Adelaide,South Australia,Business,127.160464
4,Australia,1999 Q1,Adelaide,South Australia,Business,137.448533
...,...,...,...,...,...,...
24315,Australia,2016 Q4,Yorke Peninsula,South Australia,Visiting,33.672151
24316,Australia,2017 Q1,Yorke Peninsula,South Australia,Visiting,46.223014
24317,Australia,2017 Q2,Yorke Peninsula,South Australia,Visiting,50.582837
24318,Australia,2017 Q3,Yorke Peninsula,South Australia,Visiting,27.766728
24319,Australia,2017 Q4,Yorke Peninsula,South Australia,Visiting,46.281578

In [7]:
Y_df = Y_df[['Country', 'Region', 'State', 'Purpose', 'ds', 'y']]

Y_df

,Country,Region,State,Purpose,ds,y
0,Australia,Adelaide,South Australia,Business,1998 Q1,135.077690
1,Australia,Adelaide,South Australia,Business,1998 Q2,109.987316
2,Australia,Adelaide,South Australia,Business,1998 Q3,166.034687
3,Australia,Adelaide,South Australia,Business,1998 Q4,127.160464
4,Australia,Adelaide,South Australia,Business,1999 Q1,137.448533
...,...,...,...,...,...,...
24315,Australia,Yorke Peninsula,South Australia,Visiting,2016 Q4,33.672151
24316,Australia,Yorke Peninsula,South Australia,Visiting,2017 Q1,46.223014
24317,Australia,Yorke Peninsula,South Australia,Visiting,2017 Q2,50.582837
24318,Australia,Yorke Peninsula,South Australia,Visiting,2017 Q3,27.766728
24319,Australia,Yorke Peninsula,South Australia,Visiting,2017 Q4,46.281578

In [8]:
Y_df['ds'] = Y_df['ds'].str.replace(r'(\d+) (Q\d)', r'\1-\2', regex=True)
Y_df

,Country,Region,State,Purpose,ds,y
0,Australia,Adelaide,South Australia,Business,1998-Q1,135.077690
1,Australia,Adelaide,South Australia,Business,1998-Q2,109.987316
2,Australia,Adelaide,South Australia,Business,1998-Q3,166.034687
3,Australia,Adelaide,South Australia,Business,1998-Q4,127.160464
4,Australia,Adelaide,South Australia,Business,1999-Q1,137.448533
...,...,...,...,...,...,...
24315,Australia,Yorke Peninsula,South Australia,Visiting,2016-Q4,33.672151
24316,Australia,Yorke Peninsula,South Australia,Visiting,2017-Q1,46.223014
24317,Australia,Yorke Peninsula,South Australia,Visiting,2017-Q2,50.582837
24318,Australia,Yorke Peninsula,South Australia,Visiting,2017-Q3,27.766728
24319,Australia,Yorke Peninsula,South Australia,Visiting,2017-Q4,46.281578

In [9]:
Y_df['ds'] = pd.PeriodIndex(Y_df["ds"], freq='Q').to_timestamp()
Y_df

,Country,Region,State,Purpose,ds,y
0,Australia,Adelaide,South Australia,Business,1998-01-01,135.077690
1,Australia,Adelaide,South Australia,Business,1998-04-01,109.987316
2,Australia,Adelaide,South Australia,Business,1998-07-01,166.034687
3,Australia,Adelaide,South Australia,Business,1998-10-01,127.160464
4,Australia,Adelaide,South Australia,Business,1999-01-01,137.448533
...,...,...,...,...,...,...
24315,Australia,Yorke Peninsula,South Australia,Visiting,2016-10-01,33.672151
24316,Australia,Yorke Peninsula,South Australia,Visiting,2017-01-01,46.223014
24317,Australia,Yorke Peninsula,South Australia,Visiting,2017-04-01,50.582837
24318,Australia,Yorke Peninsula,South Australia,Visiting,2017-07-01,27.766728
24319,Australia,Yorke Peninsula,South Australia,Visiting,2017-10-01,46.281578

In [10]:
spec = [
    ['Country'],
    ['Country', 'State'], 
    ['Country', 'Purpose'], 
    ['Country', 'State', 'Region'], 
    ['Country', 'State', 'Purpose'], 
    ['Country', 'State', 'Region', 'Purpose']
]

In [11]:
from hierarchicalforecast.utils import aggregate

In [12]:
%%capture
Y_df, S_df, tags = aggregate(Y_df, spec)

In [13]:
Y_df

,unique_id,ds,y
0,Australia,1998-01-01,23182.197269
1,Australia,1998-04-01,20323.380067
2,Australia,1998-07-01,19826.640511
3,Australia,1998-10-01,20830.129891
4,Australia,1999-01-01,22087.353380
...,...,...,...
33995,Australia/Western Australia/Experience Perth/V...,2016-10-01,439.699451
33996,Australia/Western Australia/Experience Perth/V...,2017-01-01,356.867038
33997,Australia/Western Australia/Experience Perth/V...,2017-04-01,302.296119
33998,Australia/Western Australia/Experience Perth/V...,2017-07-01,373.442070
33999,Australia/Western Australia/Experience Perth/V...,2017-10-01,455.316702

In [14]:
S_df

,unique_id,Australia/ACT/Canberra/Business,Australia/ACT/Canberra/Holiday,Australia/ACT/Canberra/Other,Australia/ACT/Canberra/Visiting,Australia/New South Wales/Blue Mountains/Business,Australia/New South Wales/Blue Mountains/Holiday,Australia/New South Wales/Blue Mountains/Other,Australia/New South Wales/Blue Mountains/Visiting,Australia/New South Wales/Capital Country/Business,...,Australia/Western Australia/Australia's North West/Other,Australia/Western Australia/Australia's North West/Visiting,Australia/Western Australia/Australia's South West/Business,Australia/Western Australia/Australia's South West/Holiday,Australia/Western Australia/Australia's South West/Other,Australia/Western Australia/Australia's South West/Visiting,Australia/Western Australia/Experience Perth/Business,Australia/Western Australia/Experience Perth/Holiday,Australia/Western Australia/Experience Perth/Other,Australia/Western Australia/Experience Perth/Visiting
0,Australia,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,Australia/ACT,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Australia/New South Wales,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Australia/Northern Territory,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Australia/Queensland,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420,Australia/Western Australia/Australia's South ...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
421,Australia/Western Australia/Experience Perth/B...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
422,Australia/Western Australia/Experience Perth/H...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
423,Australia/Western Australia/Experience Perth/O...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
424,Australia/Western Australia/Experience Perth/V...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [16]:
tags

{'Country': array(['Australia'], dtype=object),
 'Country/State': array(['Australia/ACT', 'Australia/New South Wales',
        'Australia/Northern Territory', 'Australia/Queensland',
        'Australia/South Australia', 'Australia/Tasmania',
        'Australia/Victoria', 'Australia/Western Australia'], dtype=object),
 'Country/Purpose': array(['Australia/Business', 'Australia/Holiday', 'Australia/Other',
        'Australia/Visiting'], dtype=object),
 'Country/State/Region': array(['Australia/ACT/Canberra',
        'Australia/New South Wales/Blue Mountains',
        'Australia/New South Wales/Capital Country',
        'Australia/New South Wales/Central Coast',
        'Australia/New South Wales/Central NSW',
        'Australia/New South Wales/Hunter',
        'Australia/New South Wales/New England North West',
        'Australia/New South Wales/North Coast NSW',
        'Australia/New South Wales/Outback NSW',
        'Australia/New South Wales/Riverina',
        'Australia/New South Wales/Snowy Mountains',
        'Australia/New South Wales/South Coast',
        'Australia/New South Wales/Sydney',
        'Australia/New South Wales/The Murray',
        'Australia/Northern Territory/Alice Springs',
        'Australia/Northern Territory/Barkly',
        'Australia/Northern Territory/Darwin',
        'Australia/Northern Territory/Kakadu Arnhem',
        'Australia/Northern Territory/Katherine Daly',
        'Australia/Northern Territory/Lasseter',
        'Australia/Northern Territory/MacDonnell',
        'Australia/Queensland/Brisbane', 'Australia/Queensland/Bundaberg',
        'Australia/Queensland/Central Queensland',
        'Australia/Queensland/Darling Downs',
        'Australia/Queensland/Fraser Coast',
        'Australia/Queensland/Gold Coast', 'Australia/Queensland/Mackay',
        'Australia/Queensland/Northern', 'Australia/Queensland/Outback',
        'Australia/Queensland/Sunshine Coast',
        'Australia/Queensland/Tropical North Queensland',
        'Australia/Queensland/Whitsundays',
        'Australia/South Australia/Adelaide',
        'Australia/South Australia/Adelaide Hills',
        'Australia/South Australia/Barossa',
        'Australia/South Australia/Clare Valley',
        'Australia/South Australia/Eyre Peninsula',
        'Australia/South Australia/Fleurieu Peninsula',
        'Australia/South Australia/Flinders Ranges and Outback',
        'Australia/South Australia/Kangaroo Island',
        'Australia/South Australia/Limestone Coast',
        'Australia/South Australia/Murraylands',
        'Australia/South Australia/Riverland',
        'Australia/South Australia/Yorke Peninsula',
        'Australia/Tasmania/East Coast',
        'Australia/Tasmania/Hobart and the South',
        'Australia/Tasmania/Launceston, Tamar and the North',
        'Australia/Tasmania/North West',
        'Australia/Tasmania/Wilderness West',
        'Australia/Victoria/Ballarat', 'Australia/Victoria/Bendigo Loddon',
        'Australia/Victoria/Central Highlands',
        'Australia/Victoria/Central Murray',
        'Australia/Victoria/Geelong and the Bellarine',
        'Australia/Victoria/Gippsland', 'Australia/Victoria/Goulburn',
        'Australia/Victoria/Great Ocean Road',
        'Australia/Victoria/High Country', 'Australia/Victoria/Lakes',
        'Australia/Victoria/Macedon', 'Australia/Victoria/Mallee',
        'Australia/Victoria/Melbourne',
        'Australia/Victoria/Melbourne East',
        'Australia/Victoria/Murray East', 'Australia/Victoria/Peninsula',
        'Australia/Victoria/Phillip Island',
        'Australia/Victoria/Spa Country', 'Australia/Victoria/Upper Yarra',
        'Australia/Victoria/Western Grampians',
        'Australia/Victoria/Wimmera',
        "Australia/Western Australia/Australia's Coral Coast",
        "Australia/Western Australia/Australia's Golden Outback",
        "Australia/Western Australia/Australia's North West",
        "Australia/Western Australia/Australia's South West",
        'Australia/Western Australia/Experience Perth'], dtype=object),
 'Country/State/Purpose': array(['Australia/ACT/Business', 'Australia/ACT/Holiday',
        'Australia/ACT/Other', 'Australia/ACT/Visiting',
        'Australia/New South Wales/Business',
        'Australia/New South Wales/Holiday',
        'Australia/New South Wales/Other',
        'Australia/New South Wales/Visiting',
        'Australia/Northern Territory/Business',
        'Australia/Northern Territory/Holiday',
        'Australia/Northern Territory/Other',
        'Australia/Northern Territory/Visiting',
        'Australia/Queensland/Business', 'Australia/Queensland/Holiday',
        'Australia/Queensland/Other', 'Australia/Queensland/Visiting',
        'Australia/South Australia/Business',
        'Australia/South Australia/Holiday',
        'Australia/South Australia/Other',
        'Australia/South Australia/Visiting',
        'Australia/Tasmania/Business', 'Australia/Tasmania/Holiday',
        'Australia/Tasmania/Other', 'Australia/Tasmania/Visiting',
        'Australia/Victoria/Business', 'Australia/Victoria/Holiday',
        'Australia/Victoria/Other', 'Australia/Victoria/Visiting',
        'Australia/Western Australia/Business',
        'Australia/Western Australia/Holiday',
        'Australia/Western Australia/Other',
        'Australia/Western Australia/Visiting'], dtype=object),
 'Country/State/Region/Purpose': array(['Australia/ACT/Canberra/Business',
        'Australia/ACT/Canberra/Holiday', 'Australia/ACT/Canberra/Other',
        'Australia/ACT/Canberra/Visiting',
        'Australia/New South Wales/Blue Mountains/Business',
        'Australia/New South Wales/Blue Mountains/Holiday',
        'Australia/New South Wales/Blue Mountains/Other',
        'Australia/New South Wales/Blue Mountains/Visiting',
        'Australia/New South Wales/Capital Country/Business',
        'Australia/New South Wales/Capital Country/Holiday',
        'Australia/New South Wales/Capital Country/Other',
        'Australia/New South Wales/Capital Country/Visiting',
        'Australia/New South Wales/Central Coast/Business',
        'Australia/New South Wales/Central Coast/Holiday',
        'Australia/New South Wales/Central Coast/Other',
        'Australia/New South Wales/Central Coast/Visiting',
        'Australia/New South Wales/Central NSW/Business',
        'Australia/New South Wales/Central NSW/Holiday',
        'Australia/New South Wales/Central NSW/Other',
        'Australia/New South Wales/Central NSW/Visiting',
        'Australia/New South Wales/Hunter/Business',
        'Australia/New South Wales/Hunter/Holiday',
        'Australia/New South Wales/Hunter/Other',
        'Australia/New South Wales/Hunter/Visiting',
        'Australia/New South Wales/New England North West/Business',
        'Australia/New South Wales/New England North West/Holiday',
        'Australia/New South Wales/New England North West/Other',
        'Australia/New South Wales/New England North West/Visiting',
        'Australia/New South Wales/North Coast NSW/Business',
        'Australia/New South Wales/North Coast NSW/Holiday',
        'Australia/New South Wales/North Coast NSW/Other',
        'Australia/New South Wales/North Coast NSW/Visiting',
        'Australia/New South Wales/Outback NSW/Business',
        'Australia/New South Wales/Outback NSW/Holiday',
        'Australia/New South Wales/Outback NSW/Other',
        'Australia/New South Wales/Outback NSW/Visiting',
        'Australia/New South Wales/Riverina/Business',
        'Australia/New South Wales/Riverina/Holiday',
        'Australia/New South Wales/Riverina/Other',
        'Australia/New South Wales/Riverina/Visiting',
        'Australia/New South Wales/Snowy Mountains/Business',
        'Australia/New South Wales/Snowy Mountains/Holiday',
        'Australia/New South Wales/Snowy Mountains/Other',
        'Australia/New South Wales/Snowy Mountains/Visiting',
        'Australia/New South Wales/South Coast/Business',
        'Australia/New South Wales/South Coast/Holiday',
        'Australia/New South Wales/South Coast/Other',
        'Australia/New South Wales/South Coast/Visiting',
        'Australia/New South Wales/Sydney/Business',
        'Australia/New South Wales/Sydney/Holiday',
        'Australia/New South Wales/Sydney/Other',
        'Australia/New South Wales/Sydney/Visiting',
        'Australia/New South Wales/The Murray/Business',
        'Australia/New South Wales/The Murray/Holiday',
        'Australia/New South Wales/The Murray/Other',
        'Australia/New South Wales/The Murray/Visiting',
        'Australia/Northern Territory/Alice Springs/Business',
        'Australia/Northern Territory/Alice Springs/Holiday',
        'Australia/Northern Territory/Alice Springs/Other',
        'Australia/Northern Territory/Alice Springs/Visiting',
        'Australia/Northern Territory/Barkly/Business',
        'Australia/Northern Territory/Barkly/Holiday',
        'Australia/Northern Territory/Barkly/Other',
        'Australia/Northern Territory/Barkly/Visiting',
        'Australia/Northern Territory/Darwin/Business',
        'Australia/Northern Territory/Darwin/Holiday',
        'Australia/Northern Territory/Darwin/Other',
        'Australia/Northern Territory/Darwin/Visiting',
        'Australia/Northern Territory/Kakadu Arnhem/Business',
        'Australia/Northern Territory/Kakadu Arnhem/Holiday',
        'Australia/Northern Territory/Kakadu Arnhem/Other',
        'Australia/Northern Territory/Kakadu Arnhem/Visiting',
        'Australia/Northern Territory/Katherine Daly/Business',
        'Australia/Northern Territory/Katherine Daly/Holiday',
        'Australia/Northern Territory/Katherine Daly/Other',
        'Australia/Northern Territory/Katherine Daly/Visiting',
        'Australia/Northern Territory/Lasseter/Business',
        'Australia/Northern Territory/Lasseter/Holiday',
        'Australia/Northern Territory/Lasseter/Other',
        'Australia/Northern Territory/Lasseter/Visiting',
        'Australia/Northern Territory/MacDonnell/Business',
        'Australia/Northern Territory/MacDonnell/Holiday',
        'Australia/Northern Territory/MacDonnell/Other',
        'Australia/Northern Territory/MacDonnell/Visiting',
        'Australia/Queensland/Brisbane/Business',
        'Australia/Queensland/Brisbane/Holiday',
        'Australia/Queensland/Brisbane/Other',
        'Australia/Queensland/Brisbane/Visiting',
        'Australia/Queensland/Bundaberg/Business',
        'Australia/Queensland/Bundaberg/Holiday',
        'Australia/Queensland/Bundaberg/Other',
        'Australia/Queensland/Bundaberg/Visiting',
        'Australia/Queensland/Central Queensland/Business',
        'Australia/Queensland/Central Queensland/Holiday',
        'Australia/Queensland/Central Queensland/Other',
        'Australia/Queensland/Central Queensland/Visiting',
        'Australia/Queensland/Darling Downs/Business',
        'Australia/Queensland/Darling Downs/Holiday',
        'Australia/Queensland/Darling Downs/Other',
        'Australia/Queensland/Darling Downs/Visiting',
        'Australia/Queensland/Fraser Coast/Business',
        'Australia/Queensland/Fraser Coast/Holiday',
        'Australia/Queensland/Fraser Coast/Other',
        'Australia/Queensland/Fraser Coast/Visiting',
        'Australia/Queensland/Gold Coast/Business',
        'Australia/Queensland/Gold Coast/Holiday',
        'Australia/Queensland/Gold Coast/Other',
        'Australia/Queensland/Gold Coast/Visiting',
        'Australia/Queensland/Mackay/Business',
        'Australia/Queensland/Mackay/Holiday',
        'Australia/Queensland/Mackay/Other',
        'Australia/Queensland/Mackay/Visiting',
        'Australia/Queensland/Northern/Business',
        'Australia/Queensland/Northern/Holiday',
        'Australia/Queensland/Northern/Other',
        'Australia/Queensland/Northern/Visiting',
        'Australia/Queensland/Outback/Business',
        'Australia/Queensland/Outback/Holiday',
        'Australia/Queensland/Outback/Other',
        'Australia/Queensland/Outback/Visiting',
        'Australia/Queensland/Sunshine Coast/Business',
        'Australia/Queensland/Sunshine Coast/Holiday',
        'Australia/Queensland/Sunshine Coast/Other',
        'Australia/Queensland/Sunshine Coast/Visiting',
        'Australia/Queensland/Tropical North Queensland/Business',
        'Australia/Queensland/Tropical North Queensland/Holiday',
        'Australia/Queensland/Tropical North Queensland/Other',
        'Australia/Queensland/Tropical North Queensland/Visiting',
        'Australia/Queensland/Whitsundays/Business',
        'Australia/Queensland/Whitsundays/Holiday',
        'Australia/Queensland/Whitsundays/Other',
        'Australia/Queensland/Whitsundays/Visiting',
        'Australia/South Australia/Adelaide Hills/Business',
        'Australia/South Australia/Adelaide Hills/Holiday',
        'Australia/South Australia/Adelaide Hills/Other',
        'Australia/South Australia/Adelaide Hills/Visiting',
        'Australia/South Australia/Adelaide/Business',
        'Australia/South Australia/Adelaide/Holiday',
        'Australia/South Australia/Adelaide/Other',
        'Australia/South Australia/Adelaide/Visiting',
        'Australia/South Australia/Barossa/Business',
        'Australia/South Australia/Barossa/Holiday',
        'Australia/South Australia/Barossa/Other',
        'Australia/South Australia/Barossa/Visiting',
        'Australia/South Australia/Clare Valley/Business',
        'Australia/South Australia/Clare Valley/Holiday',
        'Australia/South Australia/Clare Valley/Other',
        'Australia/South Australia/Clare Valley/Visiting',
        'Australia/South Australia/Eyre Peninsula/Business',
        'Australia/South Australia/Eyre Peninsula/Holiday',
        'Australia/South Australia/Eyre Peninsula/Other',
        'Australia/South Australia/Eyre Peninsula/Visiting',
        'Australia/South Australia/Fleurieu Peninsula/Business',
        'Australia/South Australia/Fleurieu Peninsula/Holiday',
        'Australia/South Australia/Fleurieu Peninsula/Other',
        'Australia/South Australia/Fleurieu Peninsula/Visiting',
        'Australia/South Australia/Flinders Ranges and Outback/Business',
        'Australia/South Australia/Flinders Ranges and Outback/Holiday',
        'Australia/South Australia/Flinders Ranges and Outback/Other',
        'Australia/South Australia/Flinders Ranges and Outback/Visiting',
        'Australia/South Australia/Kangaroo Island/Business',
        'Australia/South Australia/Kangaroo Island/Holiday',
        'Australia/South Australia/Kangaroo Island/Other',
        'Australia/South Australia/Kangaroo Island/Visiting',
        'Australia/South Australia/Limestone Coast/Business',
        'Australia/South Australia/Limestone Coast/Holiday',
        'Australia/South Australia/Limestone Coast/Other',
        'Australia/South Australia/Limestone Coast/Visiting',
        'Australia/South Australia/Murraylands/Business',
        'Australia/South Australia/Murraylands/Holiday',
        'Australia/South Australia/Murraylands/Other',
        'Australia/South Australia/Murraylands/Visiting',
        'Australia/South Australia/Riverland/Business',
        'Australia/South Australia/Riverland/Holiday',
        'Australia/South Australia/Riverland/Other',
        'Australia/South Australia/Riverland/Visiting',
        'Australia/South Australia/Yorke Peninsula/Business',
        'Australia/South Australia/Yorke Peninsula/Holiday',
        'Australia/South Australia/Yorke Peninsula/Other',
        'Australia/South Australia/Yorke Peninsula/Visiting',
        'Australia/Tasmania/East Coast/Business',
        'Australia/Tasmania/East Coast/Holiday',
        'Australia/Tasmania/East Coast/Other',
        'Australia/Tasmania/East Coast/Visiting',
        'Australia/Tasmania/Hobart and the South/Business',
        'Australia/Tasmania/Hobart and the South/Holiday',
        'Australia/Tasmania/Hobart and the South/Other',
        'Australia/Tasmania/Hobart and the South/Visiting',
        'Australia/Tasmania/Launceston, Tamar and the North/Business',
        'Australia/Tasmania/Launceston, Tamar and the North/Holiday',
        'Australia/Tasmania/Launceston, Tamar and the North/Other',
        'Australia/Tasmania/Launceston, Tamar and the North/Visiting',
        'Australia/Tasmania/North West/Business',
        'Australia/Tasmania/North West/Holiday',
        'Australia/Tasmania/North West/Other',
        'Australia/Tasmania/North West/Visiting',
        'Australia/Tasmania/Wilderness West/Business',
        'Australia/Tasmania/Wilderness West/Holiday',
        'Australia/Tasmania/Wilderness West/Other',
        'Australia/Tasmania/Wilderness West/Visiting',
        'Australia/Victoria/Ballarat/Business',
        'Australia/Victoria/Ballarat/Holiday',
        'Australia/Victoria/Ballarat/Other',
        'Australia/Victoria/Ballarat/Visiting',
        'Australia/Victoria/Bendigo Loddon/Business',
        'Australia/Victoria/Bendigo Loddon/Holiday',
        'Australia/Victoria/Bendigo Loddon/Other',
        'Australia/Victoria/Bendigo Loddon/Visiting',
        'Australia/Victoria/Central Highlands/Business',
        'Australia/Victoria/Central Highlands/Holiday',
        'Australia/Victoria/Central Highlands/Other',
        'Australia/Victoria/Central Highlands/Visiting',
        'Australia/Victoria/Central Murray/Business',
        'Australia/Victoria/Central Murray/Holiday',
        'Australia/Victoria/Central Murray/Other',
        'Australia/Victoria/Central Murray/Visiting',
        'Australia/Victoria/Geelong and the Bellarine/Business',
        'Australia/Victoria/Geelong and the Bellarine/Holiday',
        'Australia/Victoria/Geelong and the Bellarine/Other',
        'Australia/Victoria/Geelong and the Bellarine/Visiting',
        'Australia/Victoria/Gippsland/Business',
        'Australia/Victoria/Gippsland/Holiday',
        'Australia/Victoria/Gippsland/Other',
        'Australia/Victoria/Gippsland/Visiting',
        'Australia/Victoria/Goulburn/Business',
        'Australia/Victoria/Goulburn/Holiday',
        'Australia/Victoria/Goulburn/Other',
        'Australia/Victoria/Goulburn/Visiting',
        'Australia/Victoria/Great Ocean Road/Business',
        'Australia/Victoria/Great Ocean Road/Holiday',
        'Australia/Victoria/Great Ocean Road/Other',
        'Australia/Victoria/Great Ocean Road/Visiting',
        'Australia/Victoria/High Country/Business',
        'Australia/Victoria/High Country/Holiday',
        'Australia/Victoria/High Country/Other',
        'Australia/Victoria/High Country/Visiting',
        'Australia/Victoria/Lakes/Business',
        'Australia/Victoria/Lakes/Holiday',
        'Australia/Victoria/Lakes/Other',
        'Australia/Victoria/Lakes/Visiting',
        'Australia/Victoria/Macedon/Business',
        'Australia/Victoria/Macedon/Holiday',
        'Australia/Victoria/Macedon/Other',
        'Australia/Victoria/Macedon/Visiting',
        'Australia/Victoria/Mallee/Business',
        'Australia/Victoria/Mallee/Holiday',
        'Australia/Victoria/Mallee/Other',
        'Australia/Victoria/Mallee/Visiting',
        'Australia/Victoria/Melbourne East/Business',
        'Australia/Victoria/Melbourne East/Holiday',
        'Australia/Victoria/Melbourne East/Other',
        'Australia/Victoria/Melbourne East/Visiting',
        'Australia/Victoria/Melbourne/Business',
        'Australia/Victoria/Melbourne/Holiday',
        'Australia/Victoria/Melbourne/Other',
        'Australia/Victoria/Melbourne/Visiting',
        'Australia/Victoria/Murray East/Business',
        'Australia/Victoria/Murray East/Holiday',
        'Australia/Victoria/Murray East/Other',
        'Australia/Victoria/Murray East/Visiting',
        'Australia/Victoria/Peninsula/Business',
        'Australia/Victoria/Peninsula/Holiday',
        'Australia/Victoria/Peninsula/Other',
        'Australia/Victoria/Peninsula/Visiting',

In [17]:
Y_test_df = Y_df.groupby('unique_id', as_index=False).tail(8)
Y_train_df = Y_df.drop(Y_test_df.index)

In [18]:
Y_train_df.groupby('unique_id').size()

unique_id
Australia                                                72
Australia/ACT                                            72
Australia/ACT/Business                                   72
Australia/ACT/Canberra                                   72
Australia/ACT/Canberra/Business                          72
                                                         ..
Australia/Western Australia/Experience Perth/Other       72
Australia/Western Australia/Experience Perth/Visiting    72
Australia/Western Australia/Holiday                      72
Australia/Western Australia/Other                        72
Australia/Western Australia/Visiting                     72
Length: 425, dtype: int64

In [19]:
Y_test_df.groupby('unique_id').size()

unique_id
Australia                                                8
Australia/ACT                                            8
Australia/ACT/Business                                   8
Australia/ACT/Canberra                                   8
Australia/ACT/Canberra/Business                          8
                                                        ..
Australia/Western Australia/Experience Perth/Other       8
Australia/Western Australia/Experience Perth/Visiting    8
Australia/Western Australia/Holiday                      8
Australia/Western Australia/Other                        8
Australia/Western Australia/Visiting                     8
Length: 425, dtype: int64

In [20]:
%%capture
from statsforecast.models import AutoETS
from statsforecast.core import StatsForecast

In [21]:
fcst = StatsForecast(models=[AutoETS(season_length=4, model='ZZA')], 
                     freq='QS', n_jobs=-1)
Y_hat_df = fcst.forecast(df=Y_train_df, h=8, fitted=True)
Y_fitted_df = fcst.forecast_fitted_values()

In [23]:
len(Y_hat_df) , len(Y_fitted_df) , len(Y_train_df) , len(Y_test_df)

(3400, 30600, 30600, 3400)

In [25]:
Y_fitted_df.head()

   unique_id         ds             y       AutoETS
0  Australia 1998-01-01  23182.197269  22521.177714
1  Australia 1998-04-01  20323.380067  21340.083713
2  Australia 1998-07-01  19826.640511  20316.741658
3  Australia 1998-10-01  20830.129891  20646.219131
4  Australia 1999-01-01  22087.353380  22170.448469

In [26]:
from hierarchicalforecast.methods import BottomUp, MinTrace
from hierarchicalforecast.core import HierarchicalReconciliation

In [27]:
reconcilers = [
    BottomUp(),
    MinTrace(method='mint_shrink'),
    MinTrace(method='ols')
]
hrec = HierarchicalReconciliation(reconcilers=reconcilers)
Y_rec_df = hrec.reconcile(Y_hat_df=Y_hat_df, Y_df=Y_fitted_df, S_df=S_df, tags=tags)

In [33]:
Y_rec_df.head() , Y_hat_df.head()

(   unique_id         ds       AutoETS  AutoETS/BottomUp  \
 0  Australia 2016-01-01  25990.068004      24381.672903
 1  Australia 2016-04-01  24458.490282      22903.194015
 2  Australia 2016-07-01  23974.055984      22411.401316
 3  Australia 2016-10-01  24563.454495      23127.009693
 4  Australia 2017-01-01  25990.068004      24518.047370

    AutoETS/MinTrace_method-mint_shrink  AutoETS/MinTrace_method-ols
 0                         25427.793552                 25894.419896
 1                         23913.800914                 24357.231461
 2                         23428.540858                 23865.928094
 3                         24089.585592                 24470.780870
 4                         25545.039186                 25901.383310  ,
    unique_id         ds       AutoETS
 0  Australia 2016-01-01  25990.068004
 1  Australia 2016-04-01  24458.490282
 2  Australia 2016-07-01  23974.055984
 3  Australia 2016-10-01  24563.454495
 4  Australia 2017-01-01  25990.068004)

In [34]:
from hierarchicalforecast.evaluation import evaluate
from utilsforecast.losses import rmse, mase
from functools import partial

In [35]:
eval_tags = {}
eval_tags['Total'] = tags['Country']
eval_tags['Purpose'] = tags['Country/Purpose']
eval_tags['State'] = tags['Country/State']
eval_tags['Regions'] = tags['Country/State/Region']
eval_tags['Bottom'] = tags['Country/State/Region/Purpose']

In [37]:
Y_test_df.head()

    unique_id         ds             y
72  Australia 2016-01-01  26660.637689
73  Australia 2016-04-01  24285.027757
74  Australia 2016-07-01  24191.320131
75  Australia 2016-10-01  26347.600973
76  Australia 2017-01-01  27496.389021

In [39]:
Y_rec_df.head()

,unique_id,ds,AutoETS,AutoETS/BottomUp,AutoETS/MinTrace_method-mint_shrink,AutoETS/MinTrace_method-ols
0,Australia,2016-01-01,25990.068004,24381.672903,25427.793552,25894.419896
1,Australia,2016-04-01,24458.490282,22903.194015,23913.800914,24357.231461
2,Australia,2016-07-01,23974.055984,22411.401316,23428.540858,23865.928094
3,Australia,2016-10-01,24563.454495,23127.009693,24089.585592,24470.780870
4,Australia,2017-01-01,25990.068004,24518.047370,25545.039186,25901.383310

In [40]:
df = Y_rec_df.merge(Y_test_df, on=['unique_id', 'ds'])
df.head()

,unique_id,ds,AutoETS,AutoETS/BottomUp,AutoETS/MinTrace_method-mint_shrink,AutoETS/MinTrace_method-ols,y
0,Australia,2016-01-01,25990.068004,24381.672903,25427.793552,25894.419896,26660.637689
1,Australia,2016-04-01,24458.490282,22903.194015,23913.800914,24357.231461,24285.027757
2,Australia,2016-07-01,23974.055984,22411.401316,23428.540858,23865.928094,24191.320131
3,Australia,2016-10-01,24563.454495,23127.009693,24089.585592,24470.780870,26347.600973
4,Australia,2017-01-01,25990.068004,24518.047370,25545.039186,25901.383310,27496.389021

In [41]:
evaluation = evaluate(df = df,
                      tags = eval_tags,
                      train_df = Y_train_df,
                      metrics = [rmse,
                                 partial(mase, seasonality=4)])

evaluation.columns = ['level', 'metric', 'Base', 'BottomUp', 'MinTrace(mint_shrink)', 'MinTrace(ols)']
numeric_cols = evaluation.select_dtypes(include="number").columns
evaluation[numeric_cols] = evaluation[numeric_cols].map('{:.2f}'.format).astype(np.float64)

In [44]:
evaluation.query('metric == "mase"')

      level metric  Base  BottomUp  MinTrace(mint_shrink)  MinTrace(ols)
1     Total   mase  1.59      3.16                   2.06           1.67
3   Purpose   mase  1.32      2.28                   1.48           1.25
5     State   mase  1.39      1.90                   1.40           1.25
7   Regions   mase  1.12      1.19                   1.01           0.99
9    Bottom   mase  0.98      0.98                   0.94           1.01
11  Overall   mase  1.02      1.06                   0.97           1.02

In [43]:
evaluation.query('metric == "rmse"')

      level metric     Base  BottomUp  MinTrace(mint_shrink)  MinTrace(ols)
0     Total   rmse  1743.29   3029.02                2112.94        1818.94
2   Purpose   rmse   534.75    791.28                 577.18         515.53
4     State   rmse   308.15    413.44                 316.85         287.34
6   Regions   rmse    51.66     55.13                  46.55          46.29
8    Bottom   rmse    19.37     19.37                  17.80          18.19
10  Overall   rmse    41.13     49.82                  40.47          38.75